### ISSUE TITLE
Parse error from pipenv lock --requirements

### ISSUE THREAD

**Issue by glensc** [s0undt3ch/setuptools-declarative-requirements#6]
Say, if requirements.txt is generated from `pipenv lock --requirements`, it would contain a like which looks like flags:

```
-i https://pypi.org/simple/
```

this results parse error:
```
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'-i https'": Expected W:(abcd...)
```

Input file in question:
- https://github.com/Taxel/PlexTraktSync/blob/9f1806e2cf67ceb6e9309e97e6ecbae6c29113c7/requirements.txt

Full trace included of the failure:
<details>

```
➔ python -m build
* Creating venv isolated environment...
* Installing packages in isolated environment... (setuptools-declarative-requirements, setuptools>=42, wheel)
* Getting dependencies for sdist...
Traceback (most recent call last):
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 98, in __init__
    req = REQUIREMENT.parseString(requirement_string)
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1654, in parseString
    raise exc
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1644, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 3417, in parseImpl
    loc, exprtokens = e._parse( instring, loc, doActions )
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 3739, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1402, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 3400, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 1406, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/pyparsing.py", line 2711, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pkg_resources._vendor.pyparsing.ParseException: Expected W:(abcd...) (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.10.0/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 349, in <module>
    main()
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.10.0/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 331, in main
    json_out['return_val'] = hook(**hook_input['kwargs'])
  File "/Users/glen/.cache/direnv/PlexTraktSync/python-3.10.0/lib/python3.10/site-packages/pep517/in_process/_in_process.py", line 284, in get_requires_for_build_sdist
    return hook(config_settings)
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/setuptools/build_meta.py", line 159, in get_requires_for_build_sdist
    return self._get_build_requires(config_settings, requirements=[])
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/setuptools/build_meta.py", line 135, in _get_build_requires
    self.run_setup()
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/setuptools/build_meta.py", line 150, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 1, in <module>
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python@3.10/3.10.0_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/distutils/core.py", line 121, in setup
    dist.parse_config_files()
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/declarative_requirements/integration.py", line 104, in wrapper
    dist._finalize_requires()
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/setuptools/dist.py", line 528, in _finalize_requires
    self._move_install_requirements_markers()
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/setuptools/dist.py", line 567, in _move_install_requirements_markers
    inst_reqs = list(pkg_resources.parse_requirements(spec_inst_reqs))
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3084, in parse_requirements
    yield Requirement(line)
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/__init__.py", line 3094, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "/private/var/folders/jm/_gwj2_bj37g_qc4pj1xvk6fw0000gp/T/build-env-j87mq569/lib/python3.10/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 100, in __init__
    raise InvalidRequirement(
pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'-i https'": Expected W:(abcd...)

ERROR Backend subproccess exited when trying to invoke get_requires_for_build_sdist
```
</details>

**Comment by glensc** [comment]
@s0undt3ch: is this project dead? what alternative route I should use?

while releasing the package, I [added a workaround](https://github.com/Taxel/PlexTraktSync/pull/543/files) for CI, but now it's blocking installing from git repo directly:
- https://github.com/Taxel/PlexTraktSync/pull/838#issuecomment-1066712376

**Comment by s0undt3ch** [comment]
No, the project is not dead and it's being actively used in several projects.

Time to look at these issues is however scarce.

Those lines should be skipped, should be simple to add that and submit a PR?

**Comment by glensc** [comment]
https://github.com/s0undt3ch/setuptools-declarative-requirements/pull/7, but I don't know how to test.
