### ISSUE TITLE
`-r <req-file>` breaks editable install

### ISSUE THREAD

**Issue by stdedos** [s0undt3ch/setuptools-declarative-requirements#9]
For configuration:

```toml
# pyproject.toml
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "setuptools-declarative-requirements",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]

[tool.setuptools.package-data]
"*" = [
    "requirements.txt",
    "requirements-dev.txt",
    "src/<path>/requirements.txt",
]
```

```ini
; setup.cfg
[requirements-files]
install_requires = requirements.txt
tests_require = requirements-dev.txt
extras_require =
  docs = requirements-dev.txt
  dev = requirements-dev.txt
  ci = requirements-dev.txt
```

and
```requirements
networkx

-r src/<path>/requirements.txt
```

I am getting:

```console
$ pip install -e .[dev]
Obtaining file://<proj>
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [50 lines of output]
      /tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      Traceback (most recent call last):
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 102, in __init__
          req = REQUIREMENT.parseString(requirement_string)
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/pyparsing/core.py", line 1141, in parse_string
          raise exc.with_traceback(None)
      pkg_resources._vendor.pyparsing.exceptions.ParseException: Expected W:(0-9A-Za-z), found '-'  (at char 0), (line:1, col:1)
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "<proj>/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
          main()
        File "<proj>/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "<proj>/.venv/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 144, in get_requires_for_build_editable
          return hook(config_settings)
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 445, in get_requires_for_build_editable
          return self.get_requires_for_build_wheel(config_settings)
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 1, in <module>
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/declarative_requirements/integration.py", line 39, in wrapper
          func(*args, **kwargs)
        File "<proj>/.venv/lib/python3.9/site-packages/_virtualenv.py", line 21, in parse_config_files
          result = old_parse_config_files(self, *args, **kwargs)
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 868, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/config/pyprojecttoml.py", line 63, in apply_configuration
          return _apply(dist, config, filepath)
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/config/_apply_pyprojecttoml.py", line 50, in apply
          dist._finalize_requires()
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 577, in _finalize_requires
          self._move_install_requirements_markers()
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/setuptools/dist.py", line 617, in _move_install_requirements_markers
          inst_reqs = list(_reqs.parse(spec_inst_reqs))
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3102, in __init__
          super(Requirement, self).__init__(requirement_string)
        File "/tmp/pip-build-env-aqguga2x/overlay/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/requirements.py", line 104, in __init__
          raise InvalidRequirement(
      pkg_resources.extern.packaging.requirements.InvalidRequirement: Parse error at "'-r src/r'": Expected W:(0-9A-Za-z)
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

The funny thing is, both `requirements-dev.txt` **also** has `-r` lines; "but those are okay" (ignored or parsed - idk)

PS: Could you provide some insight why, instead of recursively opening the `-r <file>` and dumping its contents, parsing `-r` is a problem?

**Comment by stdedos** [comment]
... or rather, the problem might be:

```python
# requirements.txt
networkx

-r src/r<path>/requirements.txt
```

and

```python
# requirements-dev.txt
-r requirements.txt

...
```

_i.e. recursion_
